---
title: "Tuesday - Jumpstart 2025"
author: "Dan Lane"
date: "2025-08-19"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(mediation)
library(summarytools)
library(modelsummary)
library(interactions)
library(emmeans)
library(ggeffects)
library(ggplot2)
library(mediation)

#load election data
load(here("data","2020-ElectionData.rds"))
```

# Welcome to R for Communication Research!

Today In Group B we will be exploring mediation and moderation in R

## Today's Learning Goals:

-   Run basic moderation models
-   Visualize and probe moderation models (2 x 3-way interactions)
-   Simple slopes Analysis
-   Run mediation models (mediation and process packages)



## Power Analysis In R

```{r, results='asis'}

design_result <- ANOVA_design(
  design = "2b", n = 131,
  mu = c(3,3.4), sd = 1.15,
  labelnames = c("Condition","Control",
                 "Treatment"),plot = TRUE)
result_exact <- ANOVA_exact(design_result,emm = TRUE)
plot_power(design_result,
           min_n = 10, max_n = 200,
           desired_power = 80, plot = TRUE)
131*2


result_exact <- ANOVA_exact(design_result,emm = TRUE,emm_comp = "Condition")



```
